//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnthologizerClient.AnthologizerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://renoster.com/Anthologizer", ConfigurationName="AnthologizerService.IAnthologizerService")]
    public interface IAnthologizerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://renoster.com/Anthologizer/IAnthologizerService/GetComposite", ReplyAction="http://renoster.com/Anthologizer/IAnthologizerService/GetCompositeResponse")]
        com.renoster.Anthologizer.Media.Item[] GetComposite(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://renoster.com/Anthologizer/IAnthologizerService/GetComposite", ReplyAction="http://renoster.com/Anthologizer/IAnthologizerService/GetCompositeResponse")]
        System.Threading.Tasks.Task<com.renoster.Anthologizer.Media.Item[]> GetCompositeAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://renoster.com/Anthologizer/IAnthologizerService/GetAtomic", ReplyAction="http://renoster.com/Anthologizer/IAnthologizerService/GetAtomicResponse")]
        System.IO.Stream GetAtomic(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://renoster.com/Anthologizer/IAnthologizerService/GetAtomic", ReplyAction="http://renoster.com/Anthologizer/IAnthologizerService/GetAtomicResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetAtomicAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnthologizerServiceChannel : AnthologizerClient.AnthologizerService.IAnthologizerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnthologizerServiceClient : System.ServiceModel.ClientBase<AnthologizerClient.AnthologizerService.IAnthologizerService>, AnthologizerClient.AnthologizerService.IAnthologizerService {
        
        public AnthologizerServiceClient() {
        }
        
        public AnthologizerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnthologizerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnthologizerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnthologizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public com.renoster.Anthologizer.Media.Item[] GetComposite(string path) {
            return base.Channel.GetComposite(path);
        }
        
        public System.Threading.Tasks.Task<com.renoster.Anthologizer.Media.Item[]> GetCompositeAsync(string path) {
            return base.Channel.GetCompositeAsync(path);
        }
        
        public System.IO.Stream GetAtomic(string path) {
            return base.Channel.GetAtomic(path);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetAtomicAsync(string path) {
            return base.Channel.GetAtomicAsync(path);
        }
    }
}
